from enum import Enum

class MapNames(Enum):
    AYUTTHAYA = "Ayutthaya"
    BLACK_FOREST = "Black Forest"
    BLIZZARD_WORLD = "Blizzard World"
    BUSAN = "Busan"
    CASTILLO = "Castillo"
    CHATEAU_GUILLARD = "Chateau Guillard"
    DORADO = "Dorado"
    ECOPOINT_ANTARCTICA = "Ecopoint: Antarctica"
    EICHENWALDE = "Eichenwalde"
    HANAMURA = "Hanamura"
    HAVANA = "Havana"
    HOLLYWOOD = "Hollywood"
    HORIZON_LUNAR_COLONY = "Horizon Lunar Colony"
    ILIOS = "Ilios"
    JUNKERTOWN = "Junkertown"
    KANEZAKA = "Kanezaka"
    KINGS_ROW = "King's Row"
    LIJIANG_TOWER = "Lijiang Tower"
    MALEVENTO = "Malevento"
    NECROPOLIS = "Necropolis"
    NEPAL = "Nepal"
    NUMBANI = "Numbani"
    OASIS = "Oasis"
    PARIS = "Paris"
    PETRA = "Petra"
    PRACTICE_RANGE = "Practice Range"
    RIALTO = "Rialto"
    ROUTE_66 = "Route 66"
    TEMPLE_OF_ANUBIS = "Temple of Anubis"
    VOLSKAYA_INDUSTRIES = "Volskaya Industries"
    WATCHPOINT_GILBRALTAR = "Watchpoint: Gibraltar"
    WORKSHOP_CHAMBER = "Workshop Chamber"
    WORKSHOP_EXPANSE = "Workshop Expanse"
    WORKSHOP_GREEN_SCREEN = "Workshop Green Screen"
    WORKSHOP_ISLAND = "Workshop Island"

    def __str__(self) -> str:
        return self.value